<h1>Carrinho de Compras</h1>
<table>
  <tr>
    <th>ID</th>
    <th>Nome</th>
    <th>Preço</th>
    <th>Qtd.</th>
    <th>Subtotal</th>
    <th></th>
  </tr>
  <?php foreach ($carrinho as $produto): ?>
  <tr>
    <td><?= $produto->id ?></td>
    <td><?= $produto->nome ?></td>
    <td><?= $produto->preco ?></td>
    <td><?= $produto->qtd ?></td>
    <td>R$ <span><?= $produto->subtotal ?></span></td>
    <td><a href="/carrinho/adicionar?produto=<?= $produto->id ?>">Adicionar</a></td>
    <td><a href="/carrinho/remover?produto=<?= $produto->id ?>">Remover</a></td>
  </tr>
  <?php endforeach ?>
  <tr>
    <td align="right" colspan="4">TOTAL</td>
    <td>R$ <span id="total">0,00</span></td>
  </tr>
</table>
